# Generated by Django 6.0.6 on 2026-06-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjMan_app', '0002_rename_name_project_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
    ]
